version: "3"
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"

  webserver:
    build: . # Dockerfile로부터 이미지 빌드
    # image: apache/airflow:2.3.0
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./db:/opt/airflow/db
      - ./env:/opt/airflow/env
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    entrypoint: /bin/bash
    command: >
      -c "airflow db init &&
          airflow users create --username admin --firstname Seunggu --lastname Kwon --role Admin --email ksg8927@gmail.com --password 1111 &&
          airflow webserver"

  scheduler:
    build: . # Dockerfile로부터 이미지 빌드
    # image: apache/airflow:2.3.0
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./db:/opt/airflow/db
      - ./env:/opt/airflow/env
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    command: scheduler
